<?php
// Auto-generated by dev-tools/export-summit-fixture.php. Do not edit by hand.
defined( 'ABSPATH' ) || exit;

return array (
  'event' => 
  array (
    'post_title' => 'Applied AI & Machine Learning Summit 2026',
    'post_content' => '<p>Join us for the <strong>Applied AI & Machine Learning Summit 2026</strong> — three days of deep, practical sessions on shipping machine-learning systems that actually run in production.</p>
<p>From graph neural networks to high-throughput data pipelines and inference at scale, you\'ll learn from engineers and researchers who build these systems every day. Expect hands-on talks, live demos, and plenty of hallway-track networking.</p>
<ul><li>3 full days, 6+ deep-dive sessions</li><li>World-class speakers from DeepGraph Labs, ScaleStack & InferenceIO</li><li>VIP access, workshops and networking lounge</li></ul>',
    'post_excerpt' => 'Three days of practical, production-focused AI & ML sessions.',
    'meta' => 
    array (
      'etn_start_date' => '2026-09-14',
      'etn_end_date' => '2026-09-16',
      'etn_start_time' => '9:00 AM',
      'etn_end_time' => '5:00 PM',
      'event_timezone' => 'America/New_York',
      'etn_event_location' => 
      array (
        'address' => 'Nilkhet Rd, Dhaka 1000, Bangladesh',
        'place_id' => 'ChIJT55ECum4VTcRpH8ZJZwqCbc',
        'latitude' => 23.7339483,
        'longitude' => 90.3929252,
      ),
      'location' => 
      array (
        'address' => 'Nilkhet Rd, Dhaka 1000, Bangladesh',
        'place_id' => 'ChIJT55ECum4VTcRpH8ZJZwqCbc',
        'latitude' => 23.7339483,
        'longitude' => 90.3929252,
      ),
      'etn_event_location_type' => 'venue',
      'event_type' => 'offline',
      'etn_ticket_variations' => 
      array (
        0 => 
        array (
          'etn_ticket_name' => 'VIP Pass',
          'etn_ticket_price' => 499,
          'etn_avaiilable_tickets' => 100,
          'etn_sold_tickets' => 0,
          'etn_min_ticket' => 1,
          'etn_max_ticket' => 5,
          'etn_ticket_slug' => '517382-vip-pass-27fad',
          'pending' => 0,
          'optiontics_block_ids' => 
          array (
          ),
          'waiting_list_count' => 0,
        ),
        1 => 
        array (
          'etn_ticket_name' => 'Regular Pass',
          'etn_ticket_price' => 199,
          'etn_avaiilable_tickets' => 250,
          'etn_sold_tickets' => 0,
          'etn_min_ticket' => 1,
          'etn_max_ticket' => 10,
          'etn_ticket_slug' => '517382-regular-pass-6f201',
          'pending' => 0,
          'optiontics_block_ids' => 
          array (
          ),
          'waiting_list_count' => 0,
        ),
        2 => 
        array (
          'etn_ticket_name' => 'Student',
          'etn_ticket_price' => 79,
          'etn_avaiilable_tickets' => 50,
          'etn_sold_tickets' => 0,
          'etn_min_ticket' => 1,
          'etn_max_ticket' => 2,
          'etn_ticket_slug' => '517382-student-62a9a',
          'pending' => 0,
          'optiontics_block_ids' => 
          array (
          ),
          'waiting_list_count' => 0,
        ),
      ),
      'etn_total_avaiilable_tickets' => '400',
      'etn_event_faq' => 
      array (
        0 => 
        array (
          'etn_faq_title' => 'Who should attend?',
          'etn_faq_content' => 'ML engineers, data scientists, platform engineers and technical leaders who want production-grade AI knowledge.',
        ),
        1 => 
        array (
          'etn_faq_title' => 'Are meals included?',
          'etn_faq_content' => 'Yes — lunch and refreshments are included for all ticket tiers. VIP includes a networking dinner.',
        ),
        2 => 
        array (
          'etn_faq_title' => 'Will sessions be recorded?',
          'etn_faq_content' => 'All main-stage sessions are recorded and shared with attendees within two weeks.',
        ),
        3 => 
        array (
          'etn_faq_title' => 'What is the refund policy?',
          'etn_faq_content' => 'Full refunds up to 14 days before the event; 50% up to 7 days before.',
        ),
      ),
      'etn_event_socials' => 
      array (
        0 => 
        array (
          'icon' => 'etn-icon fa-facebook-f',
          'etn_social_url' => 'https://facebook.com/',
        ),
        1 => 
        array (
          'icon' => 'etn-icon fa-twitter',
          'etn_social_url' => 'https://x.com/',
        ),
        2 => 
        array (
          'icon' => 'etn-icon fa-linkedin',
          'etn_social_url' => 'https://linkedin.com/',
        ),
        3 => 
        array (
          'icon' => 'etn-icon fa-instagram',
          'etn_social_url' => 'https://instagram.com/',
        ),
      ),
      'event_layout' => '517387',
      'ticket_template' => 'style-2',
      'recurring_enabled' => 'no',
      '_tax_status' => 'none',
    ),
  ),
  'speakers' => 
  array (
    0 => 
    array (
      'title' => 'Dr. Amelia Hart',
      'designation' => 'Chief AI Scientist, DeepGraph Labs',
      'company_name' => '',
      'website_email' => 'dr-amelia-hart-preview@eventin-demo.invalid',
      'summery' => 'Amelia leads applied research on graph neural networks and has shipped ML systems used by millions.',
      'social' => 
      array (
        0 => 
        array (
          'icon' => 'fa-brands fa-linkedin-in',
          'url' => 'https://www.linkedin.com/',
        ),
        1 => 
        array (
          'icon' => 'fa-brands fa-x-twitter',
          'url' => 'https://x.com/',
        ),
      ),
    ),
    1 => 
    array (
      'title' => 'Marcus Bell',
      'designation' => 'Principal Engineer, ScaleStack',
      'company_name' => '',
      'website_email' => 'marcus-bell-preview@eventin-demo.invalid',
      'summery' => 'Marcus builds high-throughput data platforms and speaks widely on distributed systems.',
      'social' => 
      array (
        0 => 
        array (
          'icon' => 'fa-brands fa-linkedin-in',
          'url' => 'https://www.linkedin.com/',
        ),
        1 => 
        array (
          'icon' => 'fa-brands fa-x-twitter',
          'url' => 'https://x.com/',
        ),
      ),
    ),
    2 => 
    array (
      'title' => 'Priya Nair',
      'designation' => 'Head of Product, InferenceIO',
      'company_name' => '',
      'website_email' => 'priya-nair-preview@eventin-demo.invalid',
      'summery' => 'Priya turns research prototypes into products, focusing on developer experience for ML tooling.',
      'social' => 
      array (
        0 => 
        array (
          'icon' => 'fa-brands fa-linkedin-in',
          'url' => 'https://www.linkedin.com/',
        ),
        1 => 
        array (
          'icon' => 'fa-brands fa-x-twitter',
          'url' => 'https://x.com/',
        ),
      ),
    ),
  ),
  'organizers' => 
  array (
    0 => 
    array (
      'title' => 'TechWinter Events',
      'designation' => 'Lead Organizer',
      'company_name' => '',
      'website_email' => 'techwinter-events-preview@eventin-demo.invalid',
      'summery' => 'TechWinter runs premier developer conferences across the globe.',
      'social' => 
      array (
      ),
    ),
    1 => 
    array (
      'title' => 'Sofia Delacroix',
      'designation' => 'Program Chair',
      'company_name' => '',
      'website_email' => 'sofia-delacroix-preview@eventin-demo.invalid',
      'summery' => 'Sofia curates the speaker line-up and agenda for the summit.',
      'social' => 
      array (
      ),
    ),
  ),
  'schedules' => 
  array (
    0 => 
    array (
      'post_title' => 'Day 1 — Foundations',
      'meta' => 
      array (
        'etn_schedule_title' => 'Day 1 — Foundations',
        'etn_schedule_date' => '2026-09-14',
        'etn_schedule_topics' => 
        array (
          0 => 
          array (
            'etn_schedule_topic' => 'Opening Keynote: The State of Applied AI',
            'etn_shedule_start_time' => '09:00 AM',
            'etn_shedule_end_time' => '10:00 AM',
            'speakers' => 
            array (
              0 => 457,
            ),
            'etn_shedule_room' => 'Main Hall',
            'etn_shedule_objective' => 'Where applied ML is heading in the next 3 years.',
          ),
          1 => 
          array (
            'etn_schedule_topic' => 'Graph Neural Networks in Production',
            'etn_shedule_start_time' => '10:30 AM',
            'etn_shedule_end_time' => '12:00 PM',
            'speakers' => 
            array (
              0 => 457,
              1 => 458,
            ),
            'etn_shedule_room' => 'Room A',
            'etn_shedule_objective' => 'Design, train and deploy GNNs at scale.',
          ),
        ),
      ),
    ),
    1 => 
    array (
      'post_title' => 'Day 2 — Systems',
      'meta' => 
      array (
        'etn_schedule_title' => 'Day 2 — Systems',
        'etn_schedule_date' => '2026-09-15',
        'etn_schedule_topics' => 
        array (
          0 => 
          array (
            'etn_schedule_topic' => 'High-Throughput Data Pipelines',
            'etn_shedule_start_time' => '09:30 AM',
            'etn_shedule_end_time' => '11:00 AM',
            'speakers' => 
            array (
              0 => 458,
            ),
            'etn_shedule_room' => 'Room B',
            'etn_shedule_objective' => 'Stream-first architectures for ML workloads.',
          ),
          1 => 
          array (
            'etn_schedule_topic' => 'Developer Experience for ML Tooling',
            'etn_shedule_start_time' => '01:00 PM',
            'etn_shedule_end_time' => '02:30 PM',
            'speakers' => 
            array (
              0 => 459,
            ),
            'etn_shedule_room' => 'Room A',
            'etn_shedule_objective' => 'Make inference APIs a joy to build against.',
          ),
        ),
      ),
    ),
    2 => 
    array (
      'post_title' => 'Day 3 — Scaling & Wrap-up',
      'meta' => 
      array (
        'etn_schedule_title' => 'Day 3 — Scaling & Wrap-up',
        'etn_schedule_date' => '2026-09-16',
        'etn_schedule_topics' => 
        array (
          0 => 
          array (
            'etn_schedule_topic' => 'Scaling to Millions of Requests',
            'etn_shedule_start_time' => '10:00 AM',
            'etn_shedule_end_time' => '11:30 AM',
            'speakers' => 
            array (
              0 => 457,
              1 => 458,
            ),
            'etn_shedule_room' => 'Main Hall',
            'etn_shedule_objective' => 'Cache, batch and scale from prototype to production.',
          ),
          1 => 
          array (
            'etn_schedule_topic' => 'Closing Panel & Networking',
            'etn_shedule_start_time' => '02:00 PM',
            'etn_shedule_end_time' => '03:30 PM',
            'speakers' => 
            array (
              0 => 457,
              1 => 458,
              2 => 459,
            ),
            'etn_shedule_room' => 'Lounge',
            'etn_shedule_objective' => 'Q&A with all speakers, then open networking.',
          ),
        ),
      ),
    ),
  ),
  '_source_speaker_ids' => 
  array (
    0 => 457,
    1 => 458,
    2 => 459,
  ),
  '_source_organizer_ids' => 
  array (
    0 => 460,
    1 => 461,
  ),
);
